### ISSUE TITLE
toTypedList 函数似乎是多余的？

### ISSUE THREAD

**Issue by vincentlauvlwj** [bennyhuo/KotlinTuples#1]
`toTypedList` 函数似乎是多余的，我们可以修改一下 `toList`，利用类型推导机制推导出所有 component 的公共父类型：

```kotlin
fun <E1 : R, E2 : R, E3 : R, R> Tuple3<E1, E2, E3>.toList(): List<R> {
    return listOf(component1(), component2(), component3())
}
```

**Comment by vincentlauvlwj** [comment]
像上面这样定义的话，`tupleOf(1, 2, 3).toList()` 的类型就是 `List<Int>`, `tupleOf(1, 2L, "3").toList()` 的类型就是 `List<Any>`，使用起来会更方便

**Comment by vincentlauvlwj** [comment]
但是让我不解的是，`tupleOf(1, 2, 3L)` 的类型居然是 `List<Any>`，而不是我以为的 `List<Number>`，可能 Kotlin 的类型推导机制还是太弱了？

**Comment by bennyhuo** [comment]
并不多余，你如果创建的是 Int 类型的 tuple，转出来的就是 List<Int>。

关键的点在于你说的类型推导机制，这个问题我们在一年前都在群里讨论过，如果 Kotlin 支持或类型可能就不存在这个问题了。

Long 和 Int 的公共父类其实是 Any，你可以用 if else 试试。具体的原因在编译器源码里面有算法，Long 的父类包括 Number 和 Serializable，Int 也包括 Number 和 Serializable，那么你说类型推导的时候他们的公共父类应该是 Number 还是 Serializable 呢？Kotlin 没有帮我们做这个决定，它选择了 Any。类似的我试过 C# 会报错，Scala 会推导出 Number & Serializable 类型。

**Comment by vincentlauvlwj** [comment]
`List<Number>` 这里是我没有仔细看，`Int` 和 `Long` 确实有多个公共父类型，所以最后推断出 `Any` 是没毛病

**Comment by vincentlauvlwj** [comment]
但是 `toTypedList` 这里其实可以参考一下标准库里面  Triple 的代码，标准库就只有一个 `toList`，当 tuple 里面的所有元素类型都是 Int 时，返回 `List<Int>`，否则会推断出公共的父类型

```kotlin
/**
 * Represents a triad of values
 *
 * There is no meaning attached to values in this class, it can be used for any purpose.
 * Triple exhibits value semantics, i.e. two triples are equal if all three components are equal.
 * An example of decomposing it into values:
 * @sample samples.misc.Tuples.tripleDestructuring
 *
 * @param A type of the first value.
 * @param B type of the second value.
 * @param C type of the third value.
 * @property first First value.
 * @property second Second value.
 * @property third Third value.
 */
public data class Triple<out A, out B, out C>(
    public val first: A,
    public val second: B,
    public val third: C
) : Serializable {

    /**
     * Returns string representation of the [Triple] including its [first], [second] and [third] values.
     */
    public override fun toString(): String = "($first, $second, $third)"
}

/**
 * Converts this triple into a list.
 * @sample samples.misc.Tuples.tripleToList
 */
public fun <T> Triple<T, T, T>.toList(): List<T> = listOf(first, second, third)
```

我对比了一下，你的代码和标准库里面的区别在于，标准库里面的类型参数标记了 `out`，这应该就是为什么你这里必须要区分 `toList` 和 `toTypedList` 的原因吧

**Comment by bennyhuo** [comment]
Get 到你的意思了。我当时还真没多想，哈哈。

**Comment by bennyhuo** [comment]
我按你说的改了！还优化了一波代码~
